// Auto-generated from src/theme.css by scripts/generate-theme.ts

export const themeTokens = [
  '--color-error-base',
  '--color-grey-base',
  '--color-info-base',
  '--color-primary-base',
  '--color-success-base',
  '--color-warning-base',
  '--shadow-color',
  '--surface-bg',
  '--surface-bg-next',
  '--surface-border',
  '--surface-fg',
  '--surface-muted',
  '--surface-primary',
  '--surface-primary-border',
  '--surface-primary-fg',
  '--surface-primary-hover',
  '--surface-secondary',
  '--surface-secondary-border',
  '--surface-secondary-fg',
  '--surface-secondary-hover',
  '--surface-shadow',
  '--surface-subtle',
  '--theme-beige-bg',
  '--theme-beige-fg',
  '--theme-bg-0',
  '--theme-bg-1',
  '--theme-bg-2',
  '--theme-bg-3',
  '--theme-bg-4',
  '--theme-blue-bg',
  '--theme-blue-fg',
  '--theme-border',
  '--theme-chroma-scale',
  '--theme-contrast-scale',
  '--theme-duration-fast',
  '--theme-duration-normal',
  '--theme-duration-slow',
  '--theme-duration-snappy',
  '--theme-ease-default',
  '--theme-error-100',
  '--theme-error-200',
  '--theme-error-300',
  '--theme-error-400',
  '--theme-error-50',
  '--theme-error-500',
  '--theme-error-600',
  '--theme-error-700',
  '--theme-error-800',
  '--theme-error-900',
  '--theme-error-bg',
  '--theme-error-fg',
  '--theme-error-hover',
  '--theme-error-secondary-bg',
  '--theme-error-secondary-bg-hover',
  '--theme-error-secondary-border',
  '--theme-error-secondary-fg',
  '--theme-fg',
  '--theme-font-mono',
  '--theme-font-sans',
  '--theme-font-size-2xl',
  '--theme-font-size-2xs',
  '--theme-font-size-3xl',
  '--theme-font-size-4xl',
  '--theme-font-size-base',
  '--theme-font-size-lg',
  '--theme-font-size-md',
  '--theme-font-size-sm',
  '--theme-font-size-xl',
  '--theme-font-size-xs',
  '--theme-font-weight-bold',
  '--theme-font-weight-medium',
  '--theme-font-weight-normal',
  '--theme-font-weight-semibold',
  '--theme-green-bg',
  '--theme-green-fg',
  '--theme-grey-100',
  '--theme-grey-200',
  '--theme-grey-300',
  '--theme-grey-400',
  '--theme-grey-50',
  '--theme-grey-500',
  '--theme-grey-600',
  '--theme-grey-700',
  '--theme-grey-800',
  '--theme-grey-900',
  '--theme-info-100',
  '--theme-info-200',
  '--theme-info-300',
  '--theme-info-400',
  '--theme-info-50',
  '--theme-info-500',
  '--theme-info-600',
  '--theme-info-700',
  '--theme-info-800',
  '--theme-info-900',
  '--theme-info-bg',
  '--theme-info-fg',
  '--theme-info-hover',
  '--theme-info-secondary-bg',
  '--theme-info-secondary-bg-hover',
  '--theme-info-secondary-border',
  '--theme-info-secondary-fg',
  '--theme-line-height-none',
  '--theme-line-height-normal',
  '--theme-line-height-relaxed',
  '--theme-line-height-tight',
  '--theme-muted',
  '--theme-pink-bg',
  '--theme-pink-fg',
  '--theme-primary',
  '--theme-primary-100',
  '--theme-primary-200',
  '--theme-primary-300',
  '--theme-primary-400',
  '--theme-primary-50',
  '--theme-primary-500',
  '--theme-primary-600',
  '--theme-primary-700',
  '--theme-primary-800',
  '--theme-primary-900',
  '--theme-primary-border',
  '--theme-primary-fg',
  '--theme-primary-focus',
  '--theme-primary-hover',
  '--theme-primary-subtle',
  '--theme-purple-bg',
  '--theme-purple-fg',
  '--theme-radius-2xl',
  '--theme-radius-full',
  '--theme-radius-lg',
  '--theme-radius-md',
  '--theme-radius-none',
  '--theme-radius-sm',
  '--theme-radius-xl',
  '--theme-shadow-0',
  '--theme-shadow-1',
  '--theme-shadow-2',
  '--theme-size-base',
  '--theme-size-large',
  '--theme-size-small',
  '--theme-size-xSmall',
  '--theme-sky-bg',
  '--theme-sky-fg',
  '--theme-spacing-2xl',
  '--theme-spacing-2xs',
  '--theme-spacing-3xs',
  '--theme-spacing-lg',
  '--theme-spacing-md',
  '--theme-spacing-none',
  '--theme-spacing-sm',
  '--theme-spacing-xl',
  '--theme-spacing-xs',
  '--theme-step-100-c',
  '--theme-step-100-h',
  '--theme-step-100-l-dark',
  '--theme-step-100-l-light',
  '--theme-step-100-t',
  '--theme-step-200-c',
  '--theme-step-200-h',
  '--theme-step-200-l-dark',
  '--theme-step-200-l-light',
  '--theme-step-200-t',
  '--theme-step-300-c',
  '--theme-step-300-h',
  '--theme-step-300-l-dark',
  '--theme-step-300-l-light',
  '--theme-step-300-t',
  '--theme-step-400-c',
  '--theme-step-400-h',
  '--theme-step-400-l-dark',
  '--theme-step-400-l-light',
  '--theme-step-400-t',
  '--theme-step-50-c',
  '--theme-step-50-h',
  '--theme-step-50-l-dark',
  '--theme-step-50-l-light',
  '--theme-step-50-t',
  '--theme-step-500-c',
  '--theme-step-500-h',
  '--theme-step-500-l-dark',
  '--theme-step-500-l-light',
  '--theme-step-500-t',
  '--theme-step-600-c',
  '--theme-step-600-h',
  '--theme-step-600-l-dark',
  '--theme-step-600-l-light',
  '--theme-step-600-t',
  '--theme-step-700-c',
  '--theme-step-700-h',
  '--theme-step-700-l-dark',
  '--theme-step-700-l-light',
  '--theme-step-700-t',
  '--theme-step-800-c',
  '--theme-step-800-h',
  '--theme-step-800-l-dark',
  '--theme-step-800-l-light',
  '--theme-step-800-t',
  '--theme-step-900-c',
  '--theme-step-900-h',
  '--theme-step-900-l-dark',
  '--theme-step-900-l-light',
  '--theme-step-900-t',
  '--theme-subtle',
  '--theme-success-100',
  '--theme-success-200',
  '--theme-success-300',
  '--theme-success-400',
  '--theme-success-50',
  '--theme-success-500',
  '--theme-success-600',
  '--theme-success-700',
  '--theme-success-800',
  '--theme-success-900',
  '--theme-success-bg',
  '--theme-success-fg',
  '--theme-success-hover',
  '--theme-success-secondary-bg',
  '--theme-success-secondary-bg-hover',
  '--theme-success-secondary-border',
  '--theme-success-secondary-fg',
  '--theme-surface-primary',
  '--theme-warning-100',
  '--theme-warning-200',
  '--theme-warning-300',
  '--theme-warning-400',
  '--theme-warning-50',
  '--theme-warning-500',
  '--theme-warning-600',
  '--theme-warning-700',
  '--theme-warning-800',
  '--theme-warning-900',
  '--theme-warning-bg',
  '--theme-warning-fg',
  '--theme-warning-hover',
  '--theme-warning-secondary-bg',
  '--theme-warning-secondary-bg-hover',
  '--theme-warning-secondary-border',
  '--theme-warning-secondary-fg',
  '--theme-yellow-bg',
  '--theme-yellow-fg',
] as const;

export type ThemeToken = (typeof themeTokens)[number];

export const themeVars = {
  '--color-error-base': 'var(--color-error-base)',
  '--color-grey-base': 'var(--color-grey-base)',
  '--color-info-base': 'var(--color-info-base)',
  '--color-primary-base': 'var(--color-primary-base)',
  '--color-success-base': 'var(--color-success-base)',
  '--color-warning-base': 'var(--color-warning-base)',
  '--shadow-color': 'var(--shadow-color)',
  '--surface-bg': 'var(--surface-bg)',
  '--surface-bg-next': 'var(--surface-bg-next)',
  '--surface-border': 'var(--surface-border)',
  '--surface-fg': 'var(--surface-fg)',
  '--surface-muted': 'var(--surface-muted)',
  '--surface-primary': 'var(--surface-primary)',
  '--surface-primary-border': 'var(--surface-primary-border)',
  '--surface-primary-fg': 'var(--surface-primary-fg)',
  '--surface-primary-hover': 'var(--surface-primary-hover)',
  '--surface-secondary': 'var(--surface-secondary)',
  '--surface-secondary-border': 'var(--surface-secondary-border)',
  '--surface-secondary-fg': 'var(--surface-secondary-fg)',
  '--surface-secondary-hover': 'var(--surface-secondary-hover)',
  '--surface-shadow': 'var(--surface-shadow)',
  '--surface-subtle': 'var(--surface-subtle)',
  '--theme-beige-bg': 'var(--theme-beige-bg)',
  '--theme-beige-fg': 'var(--theme-beige-fg)',
  '--theme-bg-0': 'var(--theme-bg-0)',
  '--theme-bg-1': 'var(--theme-bg-1)',
  '--theme-bg-2': 'var(--theme-bg-2)',
  '--theme-bg-3': 'var(--theme-bg-3)',
  '--theme-bg-4': 'var(--theme-bg-4)',
  '--theme-blue-bg': 'var(--theme-blue-bg)',
  '--theme-blue-fg': 'var(--theme-blue-fg)',
  '--theme-border': 'var(--theme-border)',
  '--theme-chroma-scale': 'var(--theme-chroma-scale)',
  '--theme-contrast-scale': 'var(--theme-contrast-scale)',
  '--theme-duration-fast': 'var(--theme-duration-fast)',
  '--theme-duration-normal': 'var(--theme-duration-normal)',
  '--theme-duration-slow': 'var(--theme-duration-slow)',
  '--theme-duration-snappy': 'var(--theme-duration-snappy)',
  '--theme-ease-default': 'var(--theme-ease-default)',
  '--theme-error-100': 'var(--theme-error-100)',
  '--theme-error-200': 'var(--theme-error-200)',
  '--theme-error-300': 'var(--theme-error-300)',
  '--theme-error-400': 'var(--theme-error-400)',
  '--theme-error-50': 'var(--theme-error-50)',
  '--theme-error-500': 'var(--theme-error-500)',
  '--theme-error-600': 'var(--theme-error-600)',
  '--theme-error-700': 'var(--theme-error-700)',
  '--theme-error-800': 'var(--theme-error-800)',
  '--theme-error-900': 'var(--theme-error-900)',
  '--theme-error-bg': 'var(--theme-error-bg)',
  '--theme-error-fg': 'var(--theme-error-fg)',
  '--theme-error-hover': 'var(--theme-error-hover)',
  '--theme-error-secondary-bg': 'var(--theme-error-secondary-bg)',
  '--theme-error-secondary-bg-hover': 'var(--theme-error-secondary-bg-hover)',
  '--theme-error-secondary-border': 'var(--theme-error-secondary-border)',
  '--theme-error-secondary-fg': 'var(--theme-error-secondary-fg)',
  '--theme-fg': 'var(--theme-fg)',
  '--theme-font-mono': 'var(--theme-font-mono)',
  '--theme-font-sans': 'var(--theme-font-sans)',
  '--theme-font-size-2xl': 'var(--theme-font-size-2xl)',
  '--theme-font-size-2xs': 'var(--theme-font-size-2xs)',
  '--theme-font-size-3xl': 'var(--theme-font-size-3xl)',
  '--theme-font-size-4xl': 'var(--theme-font-size-4xl)',
  '--theme-font-size-base': 'var(--theme-font-size-base)',
  '--theme-font-size-lg': 'var(--theme-font-size-lg)',
  '--theme-font-size-md': 'var(--theme-font-size-md)',
  '--theme-font-size-sm': 'var(--theme-font-size-sm)',
  '--theme-font-size-xl': 'var(--theme-font-size-xl)',
  '--theme-font-size-xs': 'var(--theme-font-size-xs)',
  '--theme-font-weight-bold': 'var(--theme-font-weight-bold)',
  '--theme-font-weight-medium': 'var(--theme-font-weight-medium)',
  '--theme-font-weight-normal': 'var(--theme-font-weight-normal)',
  '--theme-font-weight-semibold': 'var(--theme-font-weight-semibold)',
  '--theme-green-bg': 'var(--theme-green-bg)',
  '--theme-green-fg': 'var(--theme-green-fg)',
  '--theme-grey-100': 'var(--theme-grey-100)',
  '--theme-grey-200': 'var(--theme-grey-200)',
  '--theme-grey-300': 'var(--theme-grey-300)',
  '--theme-grey-400': 'var(--theme-grey-400)',
  '--theme-grey-50': 'var(--theme-grey-50)',
  '--theme-grey-500': 'var(--theme-grey-500)',
  '--theme-grey-600': 'var(--theme-grey-600)',
  '--theme-grey-700': 'var(--theme-grey-700)',
  '--theme-grey-800': 'var(--theme-grey-800)',
  '--theme-grey-900': 'var(--theme-grey-900)',
  '--theme-info-100': 'var(--theme-info-100)',
  '--theme-info-200': 'var(--theme-info-200)',
  '--theme-info-300': 'var(--theme-info-300)',
  '--theme-info-400': 'var(--theme-info-400)',
  '--theme-info-50': 'var(--theme-info-50)',
  '--theme-info-500': 'var(--theme-info-500)',
  '--theme-info-600': 'var(--theme-info-600)',
  '--theme-info-700': 'var(--theme-info-700)',
  '--theme-info-800': 'var(--theme-info-800)',
  '--theme-info-900': 'var(--theme-info-900)',
  '--theme-info-bg': 'var(--theme-info-bg)',
  '--theme-info-fg': 'var(--theme-info-fg)',
  '--theme-info-hover': 'var(--theme-info-hover)',
  '--theme-info-secondary-bg': 'var(--theme-info-secondary-bg)',
  '--theme-info-secondary-bg-hover': 'var(--theme-info-secondary-bg-hover)',
  '--theme-info-secondary-border': 'var(--theme-info-secondary-border)',
  '--theme-info-secondary-fg': 'var(--theme-info-secondary-fg)',
  '--theme-line-height-none': 'var(--theme-line-height-none)',
  '--theme-line-height-normal': 'var(--theme-line-height-normal)',
  '--theme-line-height-relaxed': 'var(--theme-line-height-relaxed)',
  '--theme-line-height-tight': 'var(--theme-line-height-tight)',
  '--theme-muted': 'var(--theme-muted)',
  '--theme-pink-bg': 'var(--theme-pink-bg)',
  '--theme-pink-fg': 'var(--theme-pink-fg)',
  '--theme-primary': 'var(--theme-primary)',
  '--theme-primary-100': 'var(--theme-primary-100)',
  '--theme-primary-200': 'var(--theme-primary-200)',
  '--theme-primary-300': 'var(--theme-primary-300)',
  '--theme-primary-400': 'var(--theme-primary-400)',
  '--theme-primary-50': 'var(--theme-primary-50)',
  '--theme-primary-500': 'var(--theme-primary-500)',
  '--theme-primary-600': 'var(--theme-primary-600)',
  '--theme-primary-700': 'var(--theme-primary-700)',
  '--theme-primary-800': 'var(--theme-primary-800)',
  '--theme-primary-900': 'var(--theme-primary-900)',
  '--theme-primary-border': 'var(--theme-primary-border)',
  '--theme-primary-fg': 'var(--theme-primary-fg)',
  '--theme-primary-focus': 'var(--theme-primary-focus)',
  '--theme-primary-hover': 'var(--theme-primary-hover)',
  '--theme-primary-subtle': 'var(--theme-primary-subtle)',
  '--theme-purple-bg': 'var(--theme-purple-bg)',
  '--theme-purple-fg': 'var(--theme-purple-fg)',
  '--theme-radius-2xl': 'var(--theme-radius-2xl)',
  '--theme-radius-full': 'var(--theme-radius-full)',
  '--theme-radius-lg': 'var(--theme-radius-lg)',
  '--theme-radius-md': 'var(--theme-radius-md)',
  '--theme-radius-none': 'var(--theme-radius-none)',
  '--theme-radius-sm': 'var(--theme-radius-sm)',
  '--theme-radius-xl': 'var(--theme-radius-xl)',
  '--theme-shadow-0': 'var(--theme-shadow-0)',
  '--theme-shadow-1': 'var(--theme-shadow-1)',
  '--theme-shadow-2': 'var(--theme-shadow-2)',
  '--theme-size-base': 'var(--theme-size-base)',
  '--theme-size-large': 'var(--theme-size-large)',
  '--theme-size-small': 'var(--theme-size-small)',
  '--theme-size-xSmall': 'var(--theme-size-xSmall)',
  '--theme-sky-bg': 'var(--theme-sky-bg)',
  '--theme-sky-fg': 'var(--theme-sky-fg)',
  '--theme-spacing-2xl': 'var(--theme-spacing-2xl)',
  '--theme-spacing-2xs': 'var(--theme-spacing-2xs)',
  '--theme-spacing-3xs': 'var(--theme-spacing-3xs)',
  '--theme-spacing-lg': 'var(--theme-spacing-lg)',
  '--theme-spacing-md': 'var(--theme-spacing-md)',
  '--theme-spacing-none': 'var(--theme-spacing-none)',
  '--theme-spacing-sm': 'var(--theme-spacing-sm)',
  '--theme-spacing-xl': 'var(--theme-spacing-xl)',
  '--theme-spacing-xs': 'var(--theme-spacing-xs)',
  '--theme-step-100-c': 'var(--theme-step-100-c)',
  '--theme-step-100-h': 'var(--theme-step-100-h)',
  '--theme-step-100-l-dark': 'var(--theme-step-100-l-dark)',
  '--theme-step-100-l-light': 'var(--theme-step-100-l-light)',
  '--theme-step-100-t': 'var(--theme-step-100-t)',
  '--theme-step-200-c': 'var(--theme-step-200-c)',
  '--theme-step-200-h': 'var(--theme-step-200-h)',
  '--theme-step-200-l-dark': 'var(--theme-step-200-l-dark)',
  '--theme-step-200-l-light': 'var(--theme-step-200-l-light)',
  '--theme-step-200-t': 'var(--theme-step-200-t)',
  '--theme-step-300-c': 'var(--theme-step-300-c)',
  '--theme-step-300-h': 'var(--theme-step-300-h)',
  '--theme-step-300-l-dark': 'var(--theme-step-300-l-dark)',
  '--theme-step-300-l-light': 'var(--theme-step-300-l-light)',
  '--theme-step-300-t': 'var(--theme-step-300-t)',
  '--theme-step-400-c': 'var(--theme-step-400-c)',
  '--theme-step-400-h': 'var(--theme-step-400-h)',
  '--theme-step-400-l-dark': 'var(--theme-step-400-l-dark)',
  '--theme-step-400-l-light': 'var(--theme-step-400-l-light)',
  '--theme-step-400-t': 'var(--theme-step-400-t)',
  '--theme-step-50-c': 'var(--theme-step-50-c)',
  '--theme-step-50-h': 'var(--theme-step-50-h)',
  '--theme-step-50-l-dark': 'var(--theme-step-50-l-dark)',
  '--theme-step-50-l-light': 'var(--theme-step-50-l-light)',
  '--theme-step-50-t': 'var(--theme-step-50-t)',
  '--theme-step-500-c': 'var(--theme-step-500-c)',
  '--theme-step-500-h': 'var(--theme-step-500-h)',
  '--theme-step-500-l-dark': 'var(--theme-step-500-l-dark)',
  '--theme-step-500-l-light': 'var(--theme-step-500-l-light)',
  '--theme-step-500-t': 'var(--theme-step-500-t)',
  '--theme-step-600-c': 'var(--theme-step-600-c)',
  '--theme-step-600-h': 'var(--theme-step-600-h)',
  '--theme-step-600-l-dark': 'var(--theme-step-600-l-dark)',
  '--theme-step-600-l-light': 'var(--theme-step-600-l-light)',
  '--theme-step-600-t': 'var(--theme-step-600-t)',
  '--theme-step-700-c': 'var(--theme-step-700-c)',
  '--theme-step-700-h': 'var(--theme-step-700-h)',
  '--theme-step-700-l-dark': 'var(--theme-step-700-l-dark)',
  '--theme-step-700-l-light': 'var(--theme-step-700-l-light)',
  '--theme-step-700-t': 'var(--theme-step-700-t)',
  '--theme-step-800-c': 'var(--theme-step-800-c)',
  '--theme-step-800-h': 'var(--theme-step-800-h)',
  '--theme-step-800-l-dark': 'var(--theme-step-800-l-dark)',
  '--theme-step-800-l-light': 'var(--theme-step-800-l-light)',
  '--theme-step-800-t': 'var(--theme-step-800-t)',
  '--theme-step-900-c': 'var(--theme-step-900-c)',
  '--theme-step-900-h': 'var(--theme-step-900-h)',
  '--theme-step-900-l-dark': 'var(--theme-step-900-l-dark)',
  '--theme-step-900-l-light': 'var(--theme-step-900-l-light)',
  '--theme-step-900-t': 'var(--theme-step-900-t)',
  '--theme-subtle': 'var(--theme-subtle)',
  '--theme-success-100': 'var(--theme-success-100)',
  '--theme-success-200': 'var(--theme-success-200)',
  '--theme-success-300': 'var(--theme-success-300)',
  '--theme-success-400': 'var(--theme-success-400)',
  '--theme-success-50': 'var(--theme-success-50)',
  '--theme-success-500': 'var(--theme-success-500)',
  '--theme-success-600': 'var(--theme-success-600)',
  '--theme-success-700': 'var(--theme-success-700)',
  '--theme-success-800': 'var(--theme-success-800)',
  '--theme-success-900': 'var(--theme-success-900)',
  '--theme-success-bg': 'var(--theme-success-bg)',
  '--theme-success-fg': 'var(--theme-success-fg)',
  '--theme-success-hover': 'var(--theme-success-hover)',
  '--theme-success-secondary-bg': 'var(--theme-success-secondary-bg)',
  '--theme-success-secondary-bg-hover': 'var(--theme-success-secondary-bg-hover)',
  '--theme-success-secondary-border': 'var(--theme-success-secondary-border)',
  '--theme-success-secondary-fg': 'var(--theme-success-secondary-fg)',
  '--theme-surface-primary': 'var(--theme-surface-primary)',
  '--theme-warning-100': 'var(--theme-warning-100)',
  '--theme-warning-200': 'var(--theme-warning-200)',
  '--theme-warning-300': 'var(--theme-warning-300)',
  '--theme-warning-400': 'var(--theme-warning-400)',
  '--theme-warning-50': 'var(--theme-warning-50)',
  '--theme-warning-500': 'var(--theme-warning-500)',
  '--theme-warning-600': 'var(--theme-warning-600)',
  '--theme-warning-700': 'var(--theme-warning-700)',
  '--theme-warning-800': 'var(--theme-warning-800)',
  '--theme-warning-900': 'var(--theme-warning-900)',
  '--theme-warning-bg': 'var(--theme-warning-bg)',
  '--theme-warning-fg': 'var(--theme-warning-fg)',
  '--theme-warning-hover': 'var(--theme-warning-hover)',
  '--theme-warning-secondary-bg': 'var(--theme-warning-secondary-bg)',
  '--theme-warning-secondary-bg-hover': 'var(--theme-warning-secondary-bg-hover)',
  '--theme-warning-secondary-border': 'var(--theme-warning-secondary-border)',
  '--theme-warning-secondary-fg': 'var(--theme-warning-secondary-fg)',
  '--theme-yellow-bg': 'var(--theme-yellow-bg)',
  '--theme-yellow-fg': 'var(--theme-yellow-fg)',
} as const;
