// Auto-generated from src/theme.css by scripts/generate-theme.ts
export const vars = {
  seed: {
    error: 'var(--color-error-base)',
    grey: 'var(--color-grey-base)',
    info: 'var(--color-info-base)',
    primary: 'var(--color-primary-base)',
    success: 'var(--color-success-base)',
    warning: 'var(--color-warning-base)',
  },
  shadow: {
    '0': 'var(--theme-shadow-0)',
    '1': 'var(--theme-shadow-1)',
    '2': 'var(--theme-shadow-2)',
    color: 'var(--shadow-color)',
  },
  surface: {
    bg: {
      DEFAULT: 'var(--surface-bg)',
      next: 'var(--surface-bg-next)',
    },
    border: 'var(--surface-border)',
    fg: 'var(--surface-fg)',
    muted: 'var(--surface-muted)',
    primary: {
      DEFAULT: 'var(--theme-surface-primary)',
      border: 'var(--surface-primary-border)',
      fg: 'var(--surface-primary-fg)',
      hover: 'var(--surface-primary-hover)',
    },
    secondary: {
      DEFAULT: 'var(--surface-secondary)',
      border: 'var(--surface-secondary-border)',
      fg: 'var(--surface-secondary-fg)',
      hover: 'var(--surface-secondary-hover)',
    },
    shadow: 'var(--surface-shadow)',
    subtle: 'var(--surface-subtle)',
  },
  bg: {
    '0': 'var(--theme-bg-0)',
    '1': 'var(--theme-bg-1)',
    '2': 'var(--theme-bg-2)',
  },
  border: 'var(--theme-border)',
  chroma: {
    scale: 'var(--theme-chroma-scale)',
  },
  contrast: {
    scale: 'var(--theme-contrast-scale)',
  },
  duration: {
    fast: 'var(--theme-duration-fast)',
    normal: 'var(--theme-duration-normal)',
    slow: 'var(--theme-duration-slow)',
    snappy: 'var(--theme-duration-snappy)',
  },
  ease: {
    default: 'var(--theme-ease-default)',
  },
  error: {
    '50': 'var(--theme-error-50)',
    '600': 'var(--theme-error-600)',
    '700': 'var(--theme-error-700)',
    bg: 'var(--theme-error-bg)',
    fg: 'var(--theme-error-fg)',
    hover: 'var(--theme-error-hover)',
    secondary: {
      bg: {
        DEFAULT: 'var(--theme-error-secondary-bg)',
        hover: 'var(--theme-error-secondary-bg-hover)',
      },
      border: 'var(--theme-error-secondary-border)',
      fg: 'var(--theme-error-secondary-fg)',
    },
  },
  fg: 'var(--theme-fg)',
  font: {
    mono: 'var(--theme-font-mono)',
    sans: 'var(--theme-font-sans)',
    size: {
      '2xl': 'var(--theme-font-size-2xl)',
      '2xs': 'var(--theme-font-size-2xs)',
      '3xl': 'var(--theme-font-size-3xl)',
      '4xl': 'var(--theme-font-size-4xl)',
      base: 'var(--theme-font-size-base)',
      lg: 'var(--theme-font-size-lg)',
      md: 'var(--theme-font-size-md)',
      sm: 'var(--theme-font-size-sm)',
      xl: 'var(--theme-font-size-xl)',
      xs: 'var(--theme-font-size-xs)',
    },
    weight: {
      bold: 'var(--theme-font-weight-bold)',
      medium: 'var(--theme-font-weight-medium)',
      normal: 'var(--theme-font-weight-normal)',
      semibold: 'var(--theme-font-weight-semibold)',
    },
  },
  grey: {
    '50': 'var(--theme-grey-50)',
    '100': 'var(--theme-grey-100)',
    '200': 'var(--theme-grey-200)',
    '300': 'var(--theme-grey-300)',
    '400': 'var(--theme-grey-400)',
    '500': 'var(--theme-grey-500)',
    '600': 'var(--theme-grey-600)',
    '700': 'var(--theme-grey-700)',
    '800': 'var(--theme-grey-800)',
    '900': 'var(--theme-grey-900)',
  },
  info: {
    '50': 'var(--theme-info-50)',
    '600': 'var(--theme-info-600)',
    '700': 'var(--theme-info-700)',
    bg: 'var(--theme-info-bg)',
    fg: 'var(--theme-info-fg)',
    hover: 'var(--theme-info-hover)',
    secondary: {
      bg: {
        DEFAULT: 'var(--theme-info-secondary-bg)',
        hover: 'var(--theme-info-secondary-bg-hover)',
      },
      border: 'var(--theme-info-secondary-border)',
      fg: 'var(--theme-info-secondary-fg)',
    },
  },
  line: {
    height: {
      none: 'var(--theme-line-height-none)',
      normal: 'var(--theme-line-height-normal)',
      relaxed: 'var(--theme-line-height-relaxed)',
      tight: 'var(--theme-line-height-tight)',
    },
  },
  muted: 'var(--theme-muted)',
  primary: {
    '50': 'var(--theme-primary-50)',
    '100': 'var(--theme-primary-100)',
    '200': 'var(--theme-primary-200)',
    '300': 'var(--theme-primary-300)',
    '400': 'var(--theme-primary-400)',
    '500': 'var(--theme-primary-500)',
    '600': 'var(--theme-primary-600)',
    '700': 'var(--theme-primary-700)',
    '800': 'var(--theme-primary-800)',
    '900': 'var(--theme-primary-900)',
    DEFAULT: 'var(--theme-primary)',
    border: 'var(--theme-primary-border)',
    fg: 'var(--theme-primary-fg)',
    focus: 'var(--theme-primary-focus)',
    hover: 'var(--theme-primary-hover)',
    subtle: 'var(--theme-primary-subtle)',
  },
  radius: {
    '2xl': 'var(--theme-radius-2xl)',
    full: 'var(--theme-radius-full)',
    lg: 'var(--theme-radius-lg)',
    md: 'var(--theme-radius-md)',
    none: 'var(--theme-radius-none)',
    sm: 'var(--theme-radius-sm)',
    xl: 'var(--theme-radius-xl)',
  },
  size: {
    base: 'var(--theme-size-base)',
    large: 'var(--theme-size-large)',
    small: 'var(--theme-size-small)',
  },
  spacing: {
    '2xl': 'var(--theme-spacing-2xl)',
    '2xs': 'var(--theme-spacing-2xs)',
    '3xs': 'var(--theme-spacing-3xs)',
    lg: 'var(--theme-spacing-lg)',
    md: 'var(--theme-spacing-md)',
    none: 'var(--theme-spacing-none)',
    sm: 'var(--theme-spacing-sm)',
    xl: 'var(--theme-spacing-xl)',
    xs: 'var(--theme-spacing-xs)',
  },
  step: {
    '50': {
      c: 'var(--theme-step-50-c)',
      h: 'var(--theme-step-50-h)',
      l: {
        dark: 'var(--theme-step-50-l-dark)',
        light: 'var(--theme-step-50-l-light)',
      },
      t: 'var(--theme-step-50-t)',
    },
    '100': {
      c: 'var(--theme-step-100-c)',
      h: 'var(--theme-step-100-h)',
      l: {
        dark: 'var(--theme-step-100-l-dark)',
        light: 'var(--theme-step-100-l-light)',
      },
      t: 'var(--theme-step-100-t)',
    },
    '200': {
      c: 'var(--theme-step-200-c)',
      h: 'var(--theme-step-200-h)',
      l: {
        dark: 'var(--theme-step-200-l-dark)',
        light: 'var(--theme-step-200-l-light)',
      },
      t: 'var(--theme-step-200-t)',
    },
    '300': {
      c: 'var(--theme-step-300-c)',
      h: 'var(--theme-step-300-h)',
      l: {
        dark: 'var(--theme-step-300-l-dark)',
        light: 'var(--theme-step-300-l-light)',
      },
      t: 'var(--theme-step-300-t)',
    },
    '400': {
      c: 'var(--theme-step-400-c)',
      h: 'var(--theme-step-400-h)',
      l: {
        dark: 'var(--theme-step-400-l-dark)',
        light: 'var(--theme-step-400-l-light)',
      },
      t: 'var(--theme-step-400-t)',
    },
    '500': {
      c: 'var(--theme-step-500-c)',
      h: 'var(--theme-step-500-h)',
      l: {
        dark: 'var(--theme-step-500-l-dark)',
        light: 'var(--theme-step-500-l-light)',
      },
      t: 'var(--theme-step-500-t)',
    },
    '600': {
      c: 'var(--theme-step-600-c)',
      h: 'var(--theme-step-600-h)',
      l: {
        dark: 'var(--theme-step-600-l-dark)',
        light: 'var(--theme-step-600-l-light)',
      },
      t: 'var(--theme-step-600-t)',
    },
    '700': {
      c: 'var(--theme-step-700-c)',
      h: 'var(--theme-step-700-h)',
      l: {
        dark: 'var(--theme-step-700-l-dark)',
        light: 'var(--theme-step-700-l-light)',
      },
      t: 'var(--theme-step-700-t)',
    },
    '800': {
      c: 'var(--theme-step-800-c)',
      h: 'var(--theme-step-800-h)',
      l: {
        dark: 'var(--theme-step-800-l-dark)',
        light: 'var(--theme-step-800-l-light)',
      },
      t: 'var(--theme-step-800-t)',
    },
    '900': {
      c: 'var(--theme-step-900-c)',
      h: 'var(--theme-step-900-h)',
      l: {
        dark: 'var(--theme-step-900-l-dark)',
        light: 'var(--theme-step-900-l-light)',
      },
      t: 'var(--theme-step-900-t)',
    },
  },
  subtle: 'var(--theme-subtle)',
  success: {
    '50': 'var(--theme-success-50)',
    '500': 'var(--theme-success-500)',
    '600': 'var(--theme-success-600)',
    '700': 'var(--theme-success-700)',
    bg: 'var(--theme-success-bg)',
    fg: 'var(--theme-success-fg)',
    hover: 'var(--theme-success-hover)',
    secondary: {
      bg: {
        DEFAULT: 'var(--theme-success-secondary-bg)',
        hover: 'var(--theme-success-secondary-bg-hover)',
      },
      border: 'var(--theme-success-secondary-border)',
      fg: 'var(--theme-success-secondary-fg)',
    },
  },
  warning: {
    '50': 'var(--theme-warning-50)',
    '600': 'var(--theme-warning-600)',
    '700': 'var(--theme-warning-700)',
    bg: 'var(--theme-warning-bg)',
    fg: 'var(--theme-warning-fg)',
    hover: 'var(--theme-warning-hover)',
    secondary: {
      bg: {
        DEFAULT: 'var(--theme-warning-secondary-bg)',
        hover: 'var(--theme-warning-secondary-bg-hover)',
      },
      border: 'var(--theme-warning-secondary-border)',
      fg: 'var(--theme-warning-secondary-fg)',
    },
  },
} as const;

export const themeContract = vars;
