import path from 'node:path';
import { createJiti } from 'jiti';

const jiti = createJiti(process.cwd(), {
  interopDefault: true,
  moduleCache: false,
  jsx: true,
});

import type { CumuloPluginOptions } from '../types.js';

function matchesPattern(id: string, patterns?: (string | RegExp)[]): boolean {
  if (!patterns || patterns.length === 0) return false;
  return patterns.some((pattern) =>
    typeof pattern === 'string' ? id.includes(pattern) : pattern.test(id),
  );
}

/**
 * Checks if source code contains imports from `@cumulo/css` or `@cumulo/core`
 * or contains calls to style/recipe creation functions.
 */
export function shouldProcessFile(
  code: string,
  id: string,
  options?: CumuloPluginOptions,
): boolean {
  if (options?.exclude && matchesPattern(id, options.exclude)) {
    return false;
  }
  if (options?.include && matchesPattern(id, options.include)) {
    return true;
  }
  if (id.includes('node_modules') && !id.includes('@cumulo')) {
    return false;
  }
  if (id.endsWith('.cumulo.css') || id.includes('virtual:cumulo')) {
    return false;
  }
  if (!/\.(tsx?|jsx?|mjs|cjs)$/.test(id)) {
    return false;
  }

  return (
    code.includes('@cumulo/css') ||
    code.includes('@cumulo/core') ||
    code.includes('recipe(') ||
    code.includes('style(') ||
    code.includes('create(') ||
    code.includes('keyframes(')
  );
}

/**
 * Evaluates a file and extracts all CSS rules generated by @cumulo/css.
 */
export async function extractCssFromFile(filePath: string): Promise<string> {
  const absolutePath = path.isAbsolute(filePath) ? filePath : path.resolve(process.cwd(), filePath);

  try {
    const cumuloCss = (await jiti.import('@cumulo/css')) as typeof import('@cumulo/css');
    cumuloCss.sheet.clear();

    // Dynamically evaluate module with jiti
    await jiti.import(absolutePath);

    return cumuloCss.sheet.getCss();
  } catch (err) {
    if (process.env.DEBUG_CUMULO || process.env.NODE_ENV === 'test') {
      console.warn(`[@cumulo/unplugin] Could not evaluate ${absolutePath}:`, err);
    }
    return '';
  }
}

/**
 * Evaluates in-memory code string and extracts all CSS rules generated.
 */
export async function extractCssFromCode(code: string, id: string): Promise<string> {
  const absolutePath = path.isAbsolute(id) ? id : path.resolve(process.cwd(), id);

  try {
    const cumuloCss = (await jiti.import('@cumulo/css')) as typeof import('@cumulo/css');
    cumuloCss.sheet.clear();

    jiti.evalModule(code, {
      filename: absolutePath,
    });

    return cumuloCss.sheet.getCss();
  } catch (err) {
    if (process.env.DEBUG_CUMULO) {
      console.warn(`[@cumulo/unplugin] Could not evalModule ${absolutePath}:`, err);
    }
    return '';
  }
}
